use_frameworks!

platform :ios, '13.0'

target 'BlueshiftSDK_Example' do
  pod 'BlueshiftSDK', :path => '../'
#  pod 'BlueshiftSDK/Common', :path => '../'

  target 'BlueshiftSDK_Tests' do
    inherit! :search_paths

  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
  
end
